name: Text Ching
favicon: null
layout_spectrum: 0.54432
typography_spectrum: 0.5122167724184692
title: Engage your customers easily with texting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7262935966718942
  lightness: 0.6005443348549306
  saturation: 0.872868473874405
  rhythmicContrast: 0.007108134450390935
purpose: []
